[show interfaces] "show interfaces flap" command does not support multi-ASIC platforms (#4433)
<!--
 Please make sure you've read and understood our contributing guidelines:
 https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

 failure_prs.log skip_prs.log Make sure all your commits include a signature generated with `git commit -s` **

 If this is a bug fix, make sure your description includes "closes #xxxx",
 "fixes #xxxx" or "resolves #xxxx" so that GitHub automatically closes the related
 issue when the PR is merged.

 If you are adding/modifying/removing any command or utility script, please also
 make sure to add/modify/remove any unit tests from the tests
 directory as appropriate.

 If you are modifying or removing an existing 'show', 'config' or 'sonic-clear'
 subcommand, or you are adding a new subcommand, please make sure you also
 update the Command Line Reference Guide (doc/Command-Reference.md) to reflect
 your changes.

 Please provide the following information:
-->

#### What I did
Added multi-ASIC platform support for `show interfaces flap` command
#### How I did it
- Added `multi_asic_click_options` decorator to support `-n/--namespace` and `-d/--display` options
- Updated the command to iterate across all namespaces and aggregate flap data from each ASIC's APP_DB
- Added flap mock data to multi-ASIC mock tables (`asic0/appl_db.json`, `asic1/appl_db.json`)
- Added multi-ASIC test file `tests/flap_test.py`
#### How to verify it
```bash
# Run multi-ASIC tests
pytest tests/flap_test.py -v

# On a multi-ASIC device
show interfaces flap
show interfaces flap -n asic0
```
#### Previous command output (if the output of a command-line utility has changed)
```bash
admin@sonic:~$ show interfaces flap
Interface Flap Count Admin Oper Link Down TimeStamp(UTC) Link Up TimeStamp(UTC)
----------- ------------ ------- ------- -------------------------- ------------------------
etp1 Never Unknown Unknown Never Never
etp2 Never Unknown Unknown Never Never
etp3 Never Unknown Unknown Never Never
etp4 Never Unknown Unknown Never Never
...

admin@sonic:~$ show interfaces flap -n asic0
Usage: show interfaces flap [OPTIONS] [INTERFACENAME]
Try "show interfaces flap -h" for help.

Error: no such option: -n
```
#### New command output (if the output of a command-line utility has changed)
```bash
admin@sonic:~$ show interfaces flap
Interface Flap Count Admin Oper Link Down TimeStamp(UTC) Link Up TimeStamp(UTC)
----------- ------------ ------- ------ -------------------------- ------------------------
Ethernet0 4097 Up Up Sat Feb 21 11:00:41 2026 Sat Feb 21 11:00:59 2026
Ethernet8 4035 Up Up Sat Feb 21 11:00:41 2026 Sat Feb 21 11:00:59 2026
Ethernet16 4015 Up Up Sat Feb 21 11:01:23 2026 Sat Feb 21 11:01:41 2026
Ethernet24 4019 Up Up Sat Feb 21 11:01:23 2026 Sat Feb 21 11:01:41 2026
...

admin@sonic:~$ show interfaces flap -n asic0
Interface Flap Count Admin Oper Link Down TimeStamp(UTC) Link Up TimeStamp(UTC)
----------- ------------ ------- ------ -------------------------- ------------------------
Ethernet0 4097 Up Up Sat Feb 21 11:00:41 2026 Sat Feb 21 11:00:59 2026
Ethernet8 4035 Up Up Sat Feb 21 11:00:41 2026 Sat Feb 21 11:00:59 2026
Ethernet16 4015 Up Up Sat Feb 21 11:01:23 2026 Sat Feb 21 11:01:41 2026
Ethernet24 4019 Up Up Sat Feb 21 11:01:23 2026 Sat Feb 21 11:01:41 2026
...
```

Signed-off-by: Sonic Build Admin <sonicbld@microsoft.com>