Fix false positive "static route still bound to RIF" due to substring match on interface name (#4435)
<!--
 Please make sure you've read and understood our contributing guidelines:
 https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

 failure_prs.log skip_prs.log Make sure all your commits include a signature generated with `git commit -s` **

 If this is a bug fix, make sure your description includes "closes #xxxx",
 "fixes #xxxx" or "resolves #xxxx" so that GitHub automatically closes the related
 issue when the PR is merged.

 If you are adding/modifying/removing any command or utility script, please also
 make sure to add/modify/remove any unit tests from the tests
 directory as appropriate.

 If you are modifying or removing an existing 'show', 'config' or 'sonic-clear'
 subcommand, or you are adding a new subcommand, please make sure you also
 update the Command Line Reference Guide (doc/Command-Reference.md) to reflect
 your changes.

 Please provide the following information:
-->

#### Why I did
config interface ip remove falsely blocks IP removal when the target interface name is a substring of another interface that has a static route. For example, removing the last IP from Ethernet24 fails because "Ethernet24" in "...Ethernet240..." evaluates to True.
```
# Given: static route already exists via Ethernet240
admin@sonic:~$ show ip route vrf all static | grep Ethernet240
S>* 10.1.0.7/32 [1/0] via 18.2.202.1, Ethernet240, weight 1, 1d15h47m

# Remove IPv4 so IPv6 becomes the last IP on Ethernet24
admin@sonic:~$ sudo config interface ip remove Ethernet24 10.0.0.44/31

# Try to remove the last IP from Ethernet24
admin@sonic:~$ sudo config interface ip remove Ethernet24 FC00::59/126
Error: Cannot remove the last IP entry of interface Ethernet24. A static ip route is still bound to the RIF.
```

Despite the above error - No static route is bound to Ethernet24 -- the route is on Ethernet240.

#### What I did/How I did it
Replaced the Python in substring check with a regex word-boundary (\b) match when validating whether a static route references the interface being modified.

#### How to verify it
Before fix
```
admin@sonic:~$ sudo config interface ip remove Ethernet24 10.0.0.44/31
admin@sonic:~$ sudo config interface ip remove Ethernet24 FC00::59/126
Usage: config interface ip remove [OPTIONS] <interface_name> <ip_addr>
Try 'config interface ip remove -h' for help.

Error: Cannot remove the last IP entry of interface Ethernet24. A static ip route is still bound to the RIF.
```

After Fix
```
admin@sonic:~$ sudo config interface ip remove Ethernet24 10.0.0.44/31
admin@sonic:~$ sudo config interface ip remove Ethernet24 FC00::59/126
admin@sonic:~$
```

Signed-off-by: Sonic Build Admin <sonicbld@microsoft.com>
#### Previous command output (if the output of a command-line utility has changed)

#### New command output (if the output of a command-line utility has changed)